// +build ignore

package main

import (
	"fmt"
	"io/ioutil"
	"os"
)

// read from upstream folder and build copy of tailwindcss embedded in this project

func main() {

	out, err := os.Create("embed_gen.go")
	if err != nil {
		panic(err)
	}
	defer out.Close()

	fmt.Fprintf(out, `package twembed

// WARNING: DO NOT MODIFY, THIS FILE IS GENERATED BY embed_mk.go

`)

	var b []byte

	b, err = ioutil.ReadFile("../upstream/out/base.css")
	if err != nil {
		panic(err)
	}
	fmt.Fprintf(out, "func twbase() string {\n\treturn %q\n}\n\n", b)

	b, err = ioutil.ReadFile("../upstream/out/components.css")
	if err != nil {
		panic(err)
	}
	fmt.Fprintf(out, "func twcomponents() string {\n\treturn %q\n}\n\n", b)

	b, err = ioutil.ReadFile("../upstream/out/utilities.css")
	if err != nil {
		panic(err)
	}
	fmt.Fprintf(out, "func twutilities() string {\n\treturn %q\n}\n\n", b)

}
